"""add missing columns to tenants table

Revision ID: fa5ff3f430d2
Revises: 0ab65e1cc7fa
Create Date: 2025-06-29 13:43:20.885311

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa5ff3f430d2'
down_revision = '0ab65e1cc7fa'
branch_labels = None
depends_on = None


def upgrade():
    # Check if columns exist before adding them
    inspector = sa.inspect(op.get_bind())

    # Get existing columns for tenants table
    tenants_columns = [col['name'] for col in inspector.get_columns('tenants')]

    # Get existing columns for upload_files table
    upload_files_columns = [col['name'] for col in inspector.get_columns('upload_files')]

    # ### commands auto generated by Alembic - please adjust! ###

    # Fix tenants table
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        if 'name' not in tenants_columns:
            batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False, server_default='Default Workspace'))
        if 'encrypt_public_key' not in tenants_columns:
            batch_op.add_column(sa.Column('encrypt_public_key', sa.Text(), nullable=True))
        if 'plan' not in tenants_columns:
            batch_op.add_column(sa.Column('plan', sa.String(length=255), nullable=False, server_default='basic'))

    # Fix upload_files table - add missing columns
    with op.batch_alter_table('upload_files', schema=None) as batch_op:
        # Add storage_type column
        if 'storage_type' not in upload_files_columns:
            batch_op.add_column(sa.Column('storage_type', sa.String(length=255), server_default=sa.text("'local'::character varying"), nullable=True))

        # Add used column
        if 'used' not in upload_files_columns:
            batch_op.add_column(sa.Column('used', sa.Boolean(), nullable=False, server_default=sa.text('false')))

        # Add source_url column
        if 'source_url' not in upload_files_columns:
            batch_op.add_column(sa.Column('source_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Revert upload_files changes
    with op.batch_alter_table('upload_files', schema=None) as batch_op:
        batch_op.drop_column('hash')
        batch_op.drop_column('used_at')
        batch_op.drop_column('used_by')
        batch_op.drop_column('used')
        batch_op.drop_column('storage_type')
        # Note: created_by_role might be needed by other parts, so we don't drop it

    # Revert tenants changes
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('plan')
        batch_op.drop_column('encrypt_public_key')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
