"""add missing columns to tenants table

Revision ID: fa5ff3f430d2
Revises: 0ab65e1cc7fa
Create Date: 2025-06-29 13:43:20.885311

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa5ff3f430d2'
down_revision = '0ab65e1cc7fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False, server_default='Default Workspace'))
        batch_op.add_column(sa.Column('encrypt_public_key', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('plan', sa.String(length=255), nullable=False, server_default='basic'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('plan')
        batch_op.drop_column('encrypt_public_key')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
